

class MyError(Exception): pass

class Error(Exception):pass